// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PluginBone, PluginBoneT } from '../../solarxr-protocol/rpc/plugin-bone.js';


/**
 * Response containing the list of plugin bones.
 * Each PluginBone represents a virtual bone exposed by a plugin for tracker assignment or other purposes.
 */
export class GetPluginBonesResponse implements flatbuffers.IUnpackableObject<GetPluginBonesResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPluginBonesResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPluginBonesResponse(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesResponse):GetPluginBonesResponse {
  return (obj || new GetPluginBonesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPluginBonesResponse(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesResponse):GetPluginBonesResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPluginBonesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * List of PluginBone objects registered by loaded plugins.
 * Empty if no plugins have registered bones.
 */
bones(index: number, obj?:PluginBone):PluginBone|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PluginBone()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetPluginBonesResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBones(builder:flatbuffers.Builder, bonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bonesOffset, 0);
}

static createBonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetPluginBonesResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPluginBonesResponse(builder:flatbuffers.Builder, bonesOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetPluginBonesResponse.startGetPluginBonesResponse(builder);
  GetPluginBonesResponse.addBones(builder, bonesOffset);
  return GetPluginBonesResponse.endGetPluginBonesResponse(builder);
}

unpack(): GetPluginBonesResponseT {
  return new GetPluginBonesResponseT(
    this.bb!.createObjList<PluginBone, PluginBoneT>(this.bones.bind(this), this.bonesLength())
  );
}


unpackTo(_o: GetPluginBonesResponseT): void {
  _o.bones = this.bb!.createObjList<PluginBone, PluginBoneT>(this.bones.bind(this), this.bonesLength());
}
}

export class GetPluginBonesResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public bones: (PluginBoneT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const bones = GetPluginBonesResponse.createBonesVector(builder, builder.createObjectOffsetList(this.bones));

  return GetPluginBonesResponse.createGetPluginBonesResponse(builder,
    bones
  );
}
}
