// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Request to get currently registered plugin bone registrations from loaded plugins.
 */
export class GetPluginBonesRequest implements flatbuffers.IUnpackableObject<GetPluginBonesRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPluginBonesRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPluginBonesRequest(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesRequest):GetPluginBonesRequest {
  return (obj || new GetPluginBonesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPluginBonesRequest(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesRequest):GetPluginBonesRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPluginBonesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetPluginBonesRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetPluginBonesRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPluginBonesRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetPluginBonesRequest.startGetPluginBonesRequest(builder);
  return GetPluginBonesRequest.endGetPluginBonesRequest(builder);
}

unpack(): GetPluginBonesRequestT {
  return new GetPluginBonesRequestT();
}


unpackTo(_o: GetPluginBonesRequestT): void {}
}

export class GetPluginBonesRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return GetPluginBonesRequest.createGetPluginBonesRequest(builder);
}
}
