// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PluginBoneRegistration, PluginBoneRegistrationT } from '../../solarxr-protocol/rpc/plugin-bone-registration.js';


/**
 * Response containing the list of plugin bone registrations.
 * Each PluginBoneRegistration represents a custom bone exposed by a plugin for tracker assignment or other purposes.
 */
export class GetPluginBonesResponse implements flatbuffers.IUnpackableObject<GetPluginBonesResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPluginBonesResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPluginBonesResponse(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesResponse):GetPluginBonesResponse {
  return (obj || new GetPluginBonesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPluginBonesResponse(bb:flatbuffers.ByteBuffer, obj?:GetPluginBonesResponse):GetPluginBonesResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPluginBonesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * List of PluginBoneRegistration objects registered by loaded plugins.
 * Empty if no plugins have registered bones.
 */
registeredPluginBones(index: number, obj?:PluginBoneRegistration):PluginBoneRegistration|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PluginBoneRegistration()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

registeredPluginBonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetPluginBonesResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRegisteredPluginBones(builder:flatbuffers.Builder, registeredPluginBonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, registeredPluginBonesOffset, 0);
}

static createRegisteredPluginBonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegisteredPluginBonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetPluginBonesResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPluginBonesResponse(builder:flatbuffers.Builder, registeredPluginBonesOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetPluginBonesResponse.startGetPluginBonesResponse(builder);
  GetPluginBonesResponse.addRegisteredPluginBones(builder, registeredPluginBonesOffset);
  return GetPluginBonesResponse.endGetPluginBonesResponse(builder);
}

unpack(): GetPluginBonesResponseT {
  return new GetPluginBonesResponseT(
    this.bb!.createObjList<PluginBoneRegistration, PluginBoneRegistrationT>(this.registeredPluginBones.bind(this), this.registeredPluginBonesLength())
  );
}


unpackTo(_o: GetPluginBonesResponseT): void {
  _o.registeredPluginBones = this.bb!.createObjList<PluginBoneRegistration, PluginBoneRegistrationT>(this.registeredPluginBones.bind(this), this.registeredPluginBonesLength());
}
}

export class GetPluginBonesResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public registeredPluginBones: (PluginBoneRegistrationT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const registeredPluginBones = GetPluginBonesResponse.createRegisteredPluginBonesVector(builder, builder.createObjectOffsetList(this.registeredPluginBones));

  return GetPluginBonesResponse.createGetPluginBonesResponse(builder,
    registeredPluginBones
  );
}
}
