// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class PluginBone implements flatbuffers.IUnpackableObject<PluginBoneT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PluginBone {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPluginBone(bb:flatbuffers.ByteBuffer, obj?:PluginBone):PluginBone {
  return (obj || new PluginBone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPluginBone(bb:flatbuffers.ByteBuffer, obj?:PluginBone):PluginBone {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PluginBone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

parentBoneId():string|null
parentBoneId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
parentBoneId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

localPositionX():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localPositionY():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localPositionZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localRotationX():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localRotationY():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localRotationZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

localRotationW():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

vmcBoneName():string|null
vmcBoneName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vmcBoneName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vrcOscParamName():string|null
vrcOscParamName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vrcOscParamName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * URL to a model file (e.g., glTF/GLB) that can be attached to this bone.
 */
modelUrl():string|null
modelUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPluginBone(builder:flatbuffers.Builder) {
  builder.startObject(13);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addParentBoneId(builder:flatbuffers.Builder, parentBoneIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, parentBoneIdOffset, 0);
}

static addLocalPositionX(builder:flatbuffers.Builder, localPositionX:number) {
  builder.addFieldFloat32(3, localPositionX, 0.0);
}

static addLocalPositionY(builder:flatbuffers.Builder, localPositionY:number) {
  builder.addFieldFloat32(4, localPositionY, 0.0);
}

static addLocalPositionZ(builder:flatbuffers.Builder, localPositionZ:number) {
  builder.addFieldFloat32(5, localPositionZ, 0.0);
}

static addLocalRotationX(builder:flatbuffers.Builder, localRotationX:number) {
  builder.addFieldFloat32(6, localRotationX, 0.0);
}

static addLocalRotationY(builder:flatbuffers.Builder, localRotationY:number) {
  builder.addFieldFloat32(7, localRotationY, 0.0);
}

static addLocalRotationZ(builder:flatbuffers.Builder, localRotationZ:number) {
  builder.addFieldFloat32(8, localRotationZ, 0.0);
}

static addLocalRotationW(builder:flatbuffers.Builder, localRotationW:number) {
  builder.addFieldFloat32(9, localRotationW, 1.0);
}

static addVmcBoneName(builder:flatbuffers.Builder, vmcBoneNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, vmcBoneNameOffset, 0);
}

static addVrcOscParamName(builder:flatbuffers.Builder, vrcOscParamNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, vrcOscParamNameOffset, 0);
}

static addModelUrl(builder:flatbuffers.Builder, modelUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, modelUrlOffset, 0);
}

static endPluginBone(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPluginBone(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, parentBoneIdOffset:flatbuffers.Offset, localPositionX:number, localPositionY:number, localPositionZ:number, localRotationX:number, localRotationY:number, localRotationZ:number, localRotationW:number, vmcBoneNameOffset:flatbuffers.Offset, vrcOscParamNameOffset:flatbuffers.Offset, modelUrlOffset:flatbuffers.Offset):flatbuffers.Offset {
  PluginBone.startPluginBone(builder);
  PluginBone.addId(builder, idOffset);
  PluginBone.addName(builder, nameOffset);
  PluginBone.addParentBoneId(builder, parentBoneIdOffset);
  PluginBone.addLocalPositionX(builder, localPositionX);
  PluginBone.addLocalPositionY(builder, localPositionY);
  PluginBone.addLocalPositionZ(builder, localPositionZ);
  PluginBone.addLocalRotationX(builder, localRotationX);
  PluginBone.addLocalRotationY(builder, localRotationY);
  PluginBone.addLocalRotationZ(builder, localRotationZ);
  PluginBone.addLocalRotationW(builder, localRotationW);
  PluginBone.addVmcBoneName(builder, vmcBoneNameOffset);
  PluginBone.addVrcOscParamName(builder, vrcOscParamNameOffset);
  PluginBone.addModelUrl(builder, modelUrlOffset);
  return PluginBone.endPluginBone(builder);
}

unpack(): PluginBoneT {
  return new PluginBoneT(
    this.id(),
    this.name(),
    this.parentBoneId(),
    this.localPositionX(),
    this.localPositionY(),
    this.localPositionZ(),
    this.localRotationX(),
    this.localRotationY(),
    this.localRotationZ(),
    this.localRotationW(),
    this.vmcBoneName(),
    this.vrcOscParamName(),
    this.modelUrl()
  );
}


unpackTo(_o: PluginBoneT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.parentBoneId = this.parentBoneId();
  _o.localPositionX = this.localPositionX();
  _o.localPositionY = this.localPositionY();
  _o.localPositionZ = this.localPositionZ();
  _o.localRotationX = this.localRotationX();
  _o.localRotationY = this.localRotationY();
  _o.localRotationZ = this.localRotationZ();
  _o.localRotationW = this.localRotationW();
  _o.vmcBoneName = this.vmcBoneName();
  _o.vrcOscParamName = this.vrcOscParamName();
  _o.modelUrl = this.modelUrl();
}
}

export class PluginBoneT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public parentBoneId: string|Uint8Array|null = null,
  public localPositionX: number = 0.0,
  public localPositionY: number = 0.0,
  public localPositionZ: number = 0.0,
  public localRotationX: number = 0.0,
  public localRotationY: number = 0.0,
  public localRotationZ: number = 0.0,
  public localRotationW: number = 1.0,
  public vmcBoneName: string|Uint8Array|null = null,
  public vrcOscParamName: string|Uint8Array|null = null,
  public modelUrl: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const parentBoneId = (this.parentBoneId !== null ? builder.createString(this.parentBoneId!) : 0);
  const vmcBoneName = (this.vmcBoneName !== null ? builder.createString(this.vmcBoneName!) : 0);
  const vrcOscParamName = (this.vrcOscParamName !== null ? builder.createString(this.vrcOscParamName!) : 0);
  const modelUrl = (this.modelUrl !== null ? builder.createString(this.modelUrl!) : 0);

  return PluginBone.createPluginBone(builder,
    id,
    name,
    parentBoneId,
    this.localPositionX,
    this.localPositionY,
    this.localPositionZ,
    this.localRotationX,
    this.localRotationY,
    this.localRotationZ,
    this.localRotationW,
    vmcBoneName,
    vrcOscParamName,
    modelUrl
  );
}
}
