// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PluginBoneRegistration, PluginBoneRegistrationT } from '../../solarxr-protocol/rpc/plugin-bone-registration.js';


export class PluginBonesUpdateResponse implements flatbuffers.IUnpackableObject<PluginBonesUpdateResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PluginBonesUpdateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPluginBonesUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:PluginBonesUpdateResponse):PluginBonesUpdateResponse {
  return (obj || new PluginBonesUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPluginBonesUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:PluginBonesUpdateResponse):PluginBonesUpdateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PluginBonesUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

registeredPluginBones(index: number, obj?:PluginBoneRegistration):PluginBoneRegistration|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PluginBoneRegistration()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

registeredPluginBonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPluginBonesUpdateResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRegisteredPluginBones(builder:flatbuffers.Builder, registeredPluginBonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, registeredPluginBonesOffset, 0);
}

static createRegisteredPluginBonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegisteredPluginBonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPluginBonesUpdateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPluginBonesUpdateResponse(builder:flatbuffers.Builder, registeredPluginBonesOffset:flatbuffers.Offset):flatbuffers.Offset {
  PluginBonesUpdateResponse.startPluginBonesUpdateResponse(builder);
  PluginBonesUpdateResponse.addRegisteredPluginBones(builder, registeredPluginBonesOffset);
  return PluginBonesUpdateResponse.endPluginBonesUpdateResponse(builder);
}

unpack(): PluginBonesUpdateResponseT {
  return new PluginBonesUpdateResponseT(
    this.bb!.createObjList<PluginBoneRegistration, PluginBoneRegistrationT>(this.registeredPluginBones.bind(this), this.registeredPluginBonesLength())
  );
}


unpackTo(_o: PluginBonesUpdateResponseT): void {
  _o.registeredPluginBones = this.bb!.createObjList<PluginBoneRegistration, PluginBoneRegistrationT>(this.registeredPluginBones.bind(this), this.registeredPluginBonesLength());
}
}

export class PluginBonesUpdateResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public registeredPluginBones: (PluginBoneRegistrationT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const registeredPluginBones = PluginBonesUpdateResponse.createRegisteredPluginBonesVector(builder, builder.createObjectOffsetList(this.registeredPluginBones));

  return PluginBonesUpdateResponse.createPluginBonesUpdateResponse(builder,
    registeredPluginBones
  );
}
}
