// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class PluginBoneRegistration implements flatbuffers.IUnpackableObject<PluginBoneRegistrationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PluginBoneRegistration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPluginBoneRegistration(bb:flatbuffers.ByteBuffer, obj?:PluginBoneRegistration):PluginBoneRegistration {
  return (obj || new PluginBoneRegistration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPluginBoneRegistration(bb:flatbuffers.ByteBuffer, obj?:PluginBoneRegistration):PluginBoneRegistration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PluginBoneRegistration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

parentBoneId():string|null
parentBoneId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
parentBoneId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vmcBoneName():string|null
vmcBoneName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vmcBoneName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * URL to a model file (e.g., glTF/GLB) that can be attached to this bone.
 */
modelUrl():string|null
modelUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPluginBoneRegistration(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addParentBoneId(builder:flatbuffers.Builder, parentBoneIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, parentBoneIdOffset, 0);
}

static addVmcBoneName(builder:flatbuffers.Builder, vmcBoneNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, vmcBoneNameOffset, 0);
}

static addModelUrl(builder:flatbuffers.Builder, modelUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, modelUrlOffset, 0);
}

static endPluginBoneRegistration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPluginBoneRegistration(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, parentBoneIdOffset:flatbuffers.Offset, vmcBoneNameOffset:flatbuffers.Offset, modelUrlOffset:flatbuffers.Offset):flatbuffers.Offset {
  PluginBoneRegistration.startPluginBoneRegistration(builder);
  PluginBoneRegistration.addId(builder, idOffset);
  PluginBoneRegistration.addName(builder, nameOffset);
  PluginBoneRegistration.addParentBoneId(builder, parentBoneIdOffset);
  PluginBoneRegistration.addVmcBoneName(builder, vmcBoneNameOffset);
  PluginBoneRegistration.addModelUrl(builder, modelUrlOffset);
  return PluginBoneRegistration.endPluginBoneRegistration(builder);
}

unpack(): PluginBoneRegistrationT {
  return new PluginBoneRegistrationT(
    this.id(),
    this.name(),
    this.parentBoneId(),
    this.vmcBoneName(),
    this.modelUrl()
  );
}


unpackTo(_o: PluginBoneRegistrationT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.parentBoneId = this.parentBoneId();
  _o.vmcBoneName = this.vmcBoneName();
  _o.modelUrl = this.modelUrl();
}
}

export class PluginBoneRegistrationT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public parentBoneId: string|Uint8Array|null = null,
  public vmcBoneName: string|Uint8Array|null = null,
  public modelUrl: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const parentBoneId = (this.parentBoneId !== null ? builder.createString(this.parentBoneId!) : 0);
  const vmcBoneName = (this.vmcBoneName !== null ? builder.createString(this.vmcBoneName!) : 0);
  const modelUrl = (this.modelUrl !== null ? builder.createString(this.modelUrl!) : 0);

  return PluginBoneRegistration.createPluginBoneRegistration(builder,
    id,
    name,
    parentBoneId,
    vmcBoneName,
    modelUrl
  );
}
}
