// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PluginBone, PluginBoneT } from '../../solarxr-protocol/rpc/plugin-bone.js';


/**
 * RPC response containing an array of plugin bones.
 */
export class PluginBonesUpdateResponse implements flatbuffers.IUnpackableObject<PluginBonesUpdateResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PluginBonesUpdateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPluginBonesUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:PluginBonesUpdateResponse):PluginBonesUpdateResponse {
  return (obj || new PluginBonesUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPluginBonesUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:PluginBonesUpdateResponse):PluginBonesUpdateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PluginBonesUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bones(index: number, obj?:PluginBone):PluginBone|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PluginBone()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPluginBonesUpdateResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBones(builder:flatbuffers.Builder, bonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bonesOffset, 0);
}

static createBonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPluginBonesUpdateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPluginBonesUpdateResponse(builder:flatbuffers.Builder, bonesOffset:flatbuffers.Offset):flatbuffers.Offset {
  PluginBonesUpdateResponse.startPluginBonesUpdateResponse(builder);
  PluginBonesUpdateResponse.addBones(builder, bonesOffset);
  return PluginBonesUpdateResponse.endPluginBonesUpdateResponse(builder);
}

unpack(): PluginBonesUpdateResponseT {
  return new PluginBonesUpdateResponseT(
    this.bb!.createObjList<PluginBone, PluginBoneT>(this.bones.bind(this), this.bonesLength())
  );
}


unpackTo(_o: PluginBonesUpdateResponseT): void {
  _o.bones = this.bb!.createObjList<PluginBone, PluginBoneT>(this.bones.bind(this), this.bonesLength());
}
}

export class PluginBonesUpdateResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public bones: (PluginBoneT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const bones = PluginBonesUpdateResponse.createBonesVector(builder, builder.createObjectOffsetList(this.bones));

  return PluginBonesUpdateResponse.createPluginBonesUpdateResponse(builder,
    bones
  );
}
}
