// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * OSC Settings that are used for spatial headphone processing
 */
export class SpatialHeadphonesOscSettings implements flatbuffers.IUnpackableObject<SpatialHeadphonesOscSettingsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpatialHeadphonesOscSettings {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpatialHeadphonesOscSettings(bb:flatbuffers.ByteBuffer, obj?:SpatialHeadphonesOscSettings):SpatialHeadphonesOscSettings {
  return (obj || new SpatialHeadphonesOscSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpatialHeadphonesOscSettings(bb:flatbuffers.ByteBuffer, obj?:SpatialHeadphonesOscSettings):SpatialHeadphonesOscSettings {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpatialHeadphonesOscSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

portOut():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

address():string|null
address(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
address(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSpatialHeadphonesOscSettings(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEnabled(builder:flatbuffers.Builder, enabled:boolean) {
  builder.addFieldInt8(0, +enabled, +false);
}

static addPortOut(builder:flatbuffers.Builder, portOut:number) {
  builder.addFieldInt16(1, portOut, 0);
}

static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, addressOffset, 0);
}

static endSpatialHeadphonesOscSettings(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSpatialHeadphonesOscSettings(builder:flatbuffers.Builder, enabled:boolean, portOut:number, addressOffset:flatbuffers.Offset):flatbuffers.Offset {
  SpatialHeadphonesOscSettings.startSpatialHeadphonesOscSettings(builder);
  SpatialHeadphonesOscSettings.addEnabled(builder, enabled);
  SpatialHeadphonesOscSettings.addPortOut(builder, portOut);
  SpatialHeadphonesOscSettings.addAddress(builder, addressOffset);
  return SpatialHeadphonesOscSettings.endSpatialHeadphonesOscSettings(builder);
}

unpack(): SpatialHeadphonesOscSettingsT {
  return new SpatialHeadphonesOscSettingsT(
    this.enabled(),
    this.portOut(),
    this.address()
  );
}


unpackTo(_o: SpatialHeadphonesOscSettingsT): void {
  _o.enabled = this.enabled();
  _o.portOut = this.portOut();
  _o.address = this.address();
}
}

export class SpatialHeadphonesOscSettingsT implements flatbuffers.IGeneratedObject {
constructor(
  public enabled: boolean = false,
  public portOut: number = 0,
  public address: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const address = (this.address !== null ? builder.createString(this.address!) : 0);

  return SpatialHeadphonesOscSettings.createSpatialHeadphonesOscSettings(builder,
    this.enabled,
    this.portOut,
    address
  );
}
}
