// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Request to get currently registered plugin bones from loaded plugins.
 */
@SuppressWarnings("unused")
public final class GetPluginBonesRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static GetPluginBonesRequest getRootAsGetPluginBonesRequest(ByteBuffer _bb) { return getRootAsGetPluginBonesRequest(_bb, new GetPluginBonesRequest()); }
  public static GetPluginBonesRequest getRootAsGetPluginBonesRequest(ByteBuffer _bb, GetPluginBonesRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetPluginBonesRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startGetPluginBonesRequest(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endGetPluginBonesRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetPluginBonesRequest get(int j) { return get(new GetPluginBonesRequest(), j); }
    public GetPluginBonesRequest get(GetPluginBonesRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public GetPluginBonesRequestT unpack() {
    GetPluginBonesRequestT _o = new GetPluginBonesRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(GetPluginBonesRequestT _o) {
  }
  public static int pack(FlatBufferBuilder builder, GetPluginBonesRequestT _o) {
    if (_o == null) return 0;
    startGetPluginBonesRequest(builder);
    return endGetPluginBonesRequest(builder);
  }
}

