// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class GetPluginBonesResponseT {
  private solarxr_protocol.rpc.PluginBoneRegistrationT[] registeredPluginBones;

  public solarxr_protocol.rpc.PluginBoneRegistrationT[] getRegisteredPluginBones() { return registeredPluginBones; }

  public void setRegisteredPluginBones(solarxr_protocol.rpc.PluginBoneRegistrationT[] registeredPluginBones) { this.registeredPluginBones = registeredPluginBones; }


  public GetPluginBonesResponseT() {
    this.registeredPluginBones = null;
  }
}

