// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PluginBonesUpdateResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static PluginBonesUpdateResponse getRootAsPluginBonesUpdateResponse(ByteBuffer _bb) { return getRootAsPluginBonesUpdateResponse(_bb, new PluginBonesUpdateResponse()); }
  public static PluginBonesUpdateResponse getRootAsPluginBonesUpdateResponse(ByteBuffer _bb, PluginBonesUpdateResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PluginBonesUpdateResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.rpc.PluginBone bones(int j) { return bones(new solarxr_protocol.rpc.PluginBone(), j); }
  public solarxr_protocol.rpc.PluginBone bones(solarxr_protocol.rpc.PluginBone obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bonesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.rpc.PluginBone.Vector bonesVector() { return bonesVector(new solarxr_protocol.rpc.PluginBone.Vector()); }
  public solarxr_protocol.rpc.PluginBone.Vector bonesVector(solarxr_protocol.rpc.PluginBone.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPluginBonesUpdateResponse(FlatBufferBuilder builder,
      int bonesOffset) {
    builder.startTable(1);
    PluginBonesUpdateResponse.addBones(builder, bonesOffset);
    return PluginBonesUpdateResponse.endPluginBonesUpdateResponse(builder);
  }

  public static void startPluginBonesUpdateResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addBones(FlatBufferBuilder builder, int bonesOffset) { builder.addOffset(0, bonesOffset, 0); }
  public static int createBonesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBonesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPluginBonesUpdateResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PluginBonesUpdateResponse get(int j) { return get(new PluginBonesUpdateResponse(), j); }
    public PluginBonesUpdateResponse get(PluginBonesUpdateResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public PluginBonesUpdateResponseT unpack() {
    PluginBonesUpdateResponseT _o = new PluginBonesUpdateResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(PluginBonesUpdateResponseT _o) {
    solarxr_protocol.rpc.PluginBoneT[] _oBones = new solarxr_protocol.rpc.PluginBoneT[bonesLength()];
    for (int _j = 0; _j < bonesLength(); ++_j) {_oBones[_j] = (bones(_j) != null ? bones(_j).unpack() : null);}
    _o.setBones(_oBones);
  }
  public static int pack(FlatBufferBuilder builder, PluginBonesUpdateResponseT _o) {
    if (_o == null) return 0;
    int _bones = 0;
    if (_o.getBones() != null) {
      int[] __bones = new int[_o.getBones().length];
      int _j = 0;
      for (solarxr_protocol.rpc.PluginBoneT _e : _o.getBones()) { __bones[_j] = solarxr_protocol.rpc.PluginBone.pack(builder, _e); _j++;}
      _bones = createBonesVector(builder, __bones);
    }
    return createPluginBonesUpdateResponse(
      builder,
      _bones);
  }
}

