// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class PluginBoneT {
  private String id;
  private String name;
  private String parentBoneId;
  private float localPositionX;
  private float localPositionY;
  private float localPositionZ;
  private float localRotationX;
  private float localRotationY;
  private float localRotationZ;
  private float localRotationW;
  private String vmcBoneName;
  private String vrcOscParamName;
  private String modelUrl;

  public String getId() { return id; }

  public void setId(String id) { this.id = id; }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public String getParentBoneId() { return parentBoneId; }

  public void setParentBoneId(String parentBoneId) { this.parentBoneId = parentBoneId; }

  public float getLocalPositionX() { return localPositionX; }

  public void setLocalPositionX(float localPositionX) { this.localPositionX = localPositionX; }

  public float getLocalPositionY() { return localPositionY; }

  public void setLocalPositionY(float localPositionY) { this.localPositionY = localPositionY; }

  public float getLocalPositionZ() { return localPositionZ; }

  public void setLocalPositionZ(float localPositionZ) { this.localPositionZ = localPositionZ; }

  public float getLocalRotationX() { return localRotationX; }

  public void setLocalRotationX(float localRotationX) { this.localRotationX = localRotationX; }

  public float getLocalRotationY() { return localRotationY; }

  public void setLocalRotationY(float localRotationY) { this.localRotationY = localRotationY; }

  public float getLocalRotationZ() { return localRotationZ; }

  public void setLocalRotationZ(float localRotationZ) { this.localRotationZ = localRotationZ; }

  public float getLocalRotationW() { return localRotationW; }

  public void setLocalRotationW(float localRotationW) { this.localRotationW = localRotationW; }

  public String getVmcBoneName() { return vmcBoneName; }

  public void setVmcBoneName(String vmcBoneName) { this.vmcBoneName = vmcBoneName; }

  public String getVrcOscParamName() { return vrcOscParamName; }

  public void setVrcOscParamName(String vrcOscParamName) { this.vrcOscParamName = vrcOscParamName; }

  public String getModelUrl() { return modelUrl; }

  public void setModelUrl(String modelUrl) { this.modelUrl = modelUrl; }


  public PluginBoneT() {
    this.id = null;
    this.name = null;
    this.parentBoneId = null;
    this.localPositionX = 0.0f;
    this.localPositionY = 0.0f;
    this.localPositionZ = 0.0f;
    this.localRotationX = 0.0f;
    this.localRotationY = 0.0f;
    this.localRotationZ = 0.0f;
    this.localRotationW = 1.0f;
    this.vmcBoneName = null;
    this.vrcOscParamName = null;
    this.modelUrl = null;
  }
}

