// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Represents a generic stacked overlay bone registered by a plugin.
 */
@SuppressWarnings("unused")
public final class PluginBone extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static PluginBone getRootAsPluginBone(ByteBuffer _bb) { return getRootAsPluginBone(_bb, new PluginBone()); }
  public static PluginBone getRootAsPluginBone(ByteBuffer _bb, PluginBone obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PluginBone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Unique identifier for this plugin bone.
   */
  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   * Display name of the bone (e.g., "LeftHand", "RightFoot").
   */
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  /**
   * The parent bone ID - can be a standard BodyPart name or another PluginBone's id.
   */
  public String parentBoneId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentBoneIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer parentBoneIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  /**
   * Local position relative to the parent bone in meters.
   */
  public float localPositionX() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float localPositionY() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float localPositionZ() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  /**
   * Local rotation as a quaternion (x, y, z, w) relative to the parent bone.
   */
  public float localRotationX() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float localRotationY() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float localRotationZ() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float localRotationW() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f; }
  /**
   * VMC bone name for virtual machine compatibility.
   */
  public String vmcBoneName() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer vmcBoneNameAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer vmcBoneNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  /**
   * VRChat OSC parameter name for this bone.
   */
  public String vrcOscParamName() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer vrcOscParamNameAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer vrcOscParamNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  /**
   * URL to a model file (e.g., glTF/GLB) that can be attached to this bone.
   */
  public String modelUrl() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modelUrlAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer modelUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }

  public static int createPluginBone(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset,
      int parentBoneIdOffset,
      float localPositionX,
      float localPositionY,
      float localPositionZ,
      float localRotationX,
      float localRotationY,
      float localRotationZ,
      float localRotationW,
      int vmcBoneNameOffset,
      int vrcOscParamNameOffset,
      int modelUrlOffset) {
    builder.startTable(13);
    PluginBone.addModelUrl(builder, modelUrlOffset);
    PluginBone.addVrcOscParamName(builder, vrcOscParamNameOffset);
    PluginBone.addVmcBoneName(builder, vmcBoneNameOffset);
    PluginBone.addLocalRotationW(builder, localRotationW);
    PluginBone.addLocalRotationZ(builder, localRotationZ);
    PluginBone.addLocalRotationY(builder, localRotationY);
    PluginBone.addLocalRotationX(builder, localRotationX);
    PluginBone.addLocalPositionZ(builder, localPositionZ);
    PluginBone.addLocalPositionY(builder, localPositionY);
    PluginBone.addLocalPositionX(builder, localPositionX);
    PluginBone.addParentBoneId(builder, parentBoneIdOffset);
    PluginBone.addName(builder, nameOffset);
    PluginBone.addId(builder, idOffset);
    return PluginBone.endPluginBone(builder);
  }

  public static void startPluginBone(FlatBufferBuilder builder) { builder.startTable(13); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addParentBoneId(FlatBufferBuilder builder, int parentBoneIdOffset) { builder.addOffset(2, parentBoneIdOffset, 0); }
  public static void addLocalPositionX(FlatBufferBuilder builder, float localPositionX) { builder.addFloat(3, localPositionX, 0.0f); }
  public static void addLocalPositionY(FlatBufferBuilder builder, float localPositionY) { builder.addFloat(4, localPositionY, 0.0f); }
  public static void addLocalPositionZ(FlatBufferBuilder builder, float localPositionZ) { builder.addFloat(5, localPositionZ, 0.0f); }
  public static void addLocalRotationX(FlatBufferBuilder builder, float localRotationX) { builder.addFloat(6, localRotationX, 0.0f); }
  public static void addLocalRotationY(FlatBufferBuilder builder, float localRotationY) { builder.addFloat(7, localRotationY, 0.0f); }
  public static void addLocalRotationZ(FlatBufferBuilder builder, float localRotationZ) { builder.addFloat(8, localRotationZ, 0.0f); }
  public static void addLocalRotationW(FlatBufferBuilder builder, float localRotationW) { builder.addFloat(9, localRotationW, 1.0f); }
  public static void addVmcBoneName(FlatBufferBuilder builder, int vmcBoneNameOffset) { builder.addOffset(10, vmcBoneNameOffset, 0); }
  public static void addVrcOscParamName(FlatBufferBuilder builder, int vrcOscParamNameOffset) { builder.addOffset(11, vrcOscParamNameOffset, 0); }
  public static void addModelUrl(FlatBufferBuilder builder, int modelUrlOffset) { builder.addOffset(12, modelUrlOffset, 0); }
  public static int endPluginBone(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PluginBone get(int j) { return get(new PluginBone(), j); }
    public PluginBone get(PluginBone obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public PluginBoneT unpack() {
    PluginBoneT _o = new PluginBoneT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(PluginBoneT _o) {
    String _oId = id();
    _o.setId(_oId);
    String _oName = name();
    _o.setName(_oName);
    String _oParentBoneId = parentBoneId();
    _o.setParentBoneId(_oParentBoneId);
    float _oLocalPositionX = localPositionX();
    _o.setLocalPositionX(_oLocalPositionX);
    float _oLocalPositionY = localPositionY();
    _o.setLocalPositionY(_oLocalPositionY);
    float _oLocalPositionZ = localPositionZ();
    _o.setLocalPositionZ(_oLocalPositionZ);
    float _oLocalRotationX = localRotationX();
    _o.setLocalRotationX(_oLocalRotationX);
    float _oLocalRotationY = localRotationY();
    _o.setLocalRotationY(_oLocalRotationY);
    float _oLocalRotationZ = localRotationZ();
    _o.setLocalRotationZ(_oLocalRotationZ);
    float _oLocalRotationW = localRotationW();
    _o.setLocalRotationW(_oLocalRotationW);
    String _oVmcBoneName = vmcBoneName();
    _o.setVmcBoneName(_oVmcBoneName);
    String _oVrcOscParamName = vrcOscParamName();
    _o.setVrcOscParamName(_oVrcOscParamName);
    String _oModelUrl = modelUrl();
    _o.setModelUrl(_oModelUrl);
  }
  public static int pack(FlatBufferBuilder builder, PluginBoneT _o) {
    if (_o == null) return 0;
    int _id = _o.getId() == null ? 0 : builder.createString(_o.getId());
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    int _parentBoneId = _o.getParentBoneId() == null ? 0 : builder.createString(_o.getParentBoneId());
    int _vmcBoneName = _o.getVmcBoneName() == null ? 0 : builder.createString(_o.getVmcBoneName());
    int _vrcOscParamName = _o.getVrcOscParamName() == null ? 0 : builder.createString(_o.getVrcOscParamName());
    int _modelUrl = _o.getModelUrl() == null ? 0 : builder.createString(_o.getModelUrl());
    return createPluginBone(
      builder,
      _id,
      _name,
      _parentBoneId,
      _o.getLocalPositionX(),
      _o.getLocalPositionY(),
      _o.getLocalPositionZ(),
      _o.getLocalRotationX(),
      _o.getLocalRotationY(),
      _o.getLocalRotationZ(),
      _o.getLocalRotationW(),
      _vmcBoneName,
      _vrcOscParamName,
      _modelUrl);
  }
}

