// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PluginBoneRegistration extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static PluginBoneRegistration getRootAsPluginBoneRegistration(ByteBuffer _bb) { return getRootAsPluginBoneRegistration(_bb, new PluginBoneRegistration()); }
  public static PluginBoneRegistration getRootAsPluginBoneRegistration(ByteBuffer _bb, PluginBoneRegistration obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PluginBoneRegistration __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String parentBoneId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer parentBoneIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer parentBoneIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String vmcBoneName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer vmcBoneNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer vmcBoneNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  /**
   * URL to a model file (e.g., glTF/GLB) that can be attached to this bone.
   */
  public String modelUrl() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modelUrlAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer modelUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createPluginBoneRegistration(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset,
      int parentBoneIdOffset,
      int vmcBoneNameOffset,
      int modelUrlOffset) {
    builder.startTable(5);
    PluginBoneRegistration.addModelUrl(builder, modelUrlOffset);
    PluginBoneRegistration.addVmcBoneName(builder, vmcBoneNameOffset);
    PluginBoneRegistration.addParentBoneId(builder, parentBoneIdOffset);
    PluginBoneRegistration.addName(builder, nameOffset);
    PluginBoneRegistration.addId(builder, idOffset);
    return PluginBoneRegistration.endPluginBoneRegistration(builder);
  }

  public static void startPluginBoneRegistration(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addParentBoneId(FlatBufferBuilder builder, int parentBoneIdOffset) { builder.addOffset(2, parentBoneIdOffset, 0); }
  public static void addVmcBoneName(FlatBufferBuilder builder, int vmcBoneNameOffset) { builder.addOffset(3, vmcBoneNameOffset, 0); }
  public static void addModelUrl(FlatBufferBuilder builder, int modelUrlOffset) { builder.addOffset(4, modelUrlOffset, 0); }
  public static int endPluginBoneRegistration(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PluginBoneRegistration get(int j) { return get(new PluginBoneRegistration(), j); }
    public PluginBoneRegistration get(PluginBoneRegistration obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public PluginBoneRegistrationT unpack() {
    PluginBoneRegistrationT _o = new PluginBoneRegistrationT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(PluginBoneRegistrationT _o) {
    String _oId = id();
    _o.setId(_oId);
    String _oName = name();
    _o.setName(_oName);
    String _oParentBoneId = parentBoneId();
    _o.setParentBoneId(_oParentBoneId);
    String _oVmcBoneName = vmcBoneName();
    _o.setVmcBoneName(_oVmcBoneName);
    String _oModelUrl = modelUrl();
    _o.setModelUrl(_oModelUrl);
  }
  public static int pack(FlatBufferBuilder builder, PluginBoneRegistrationT _o) {
    if (_o == null) return 0;
    int _id = _o.getId() == null ? 0 : builder.createString(_o.getId());
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    int _parentBoneId = _o.getParentBoneId() == null ? 0 : builder.createString(_o.getParentBoneId());
    int _vmcBoneName = _o.getVmcBoneName() == null ? 0 : builder.createString(_o.getVmcBoneName());
    int _modelUrl = _o.getModelUrl() == null ? 0 : builder.createString(_o.getModelUrl());
    return createPluginBoneRegistration(
      builder,
      _id,
      _name,
      _parentBoneId,
      _vmcBoneName,
      _modelUrl);
  }
}

