// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class PluginBonesUpdateResponseT {
  private solarxr_protocol.rpc.PluginBoneT[] bones;

  public solarxr_protocol.rpc.PluginBoneT[] getBones() { return bones; }

  public void setBones(solarxr_protocol.rpc.PluginBoneT[] bones) { this.bones = bones; }


  public PluginBonesUpdateResponseT() {
    this.bones = null;
  }
}

