// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class PluginBoneRegistrationT {
  private String id;
  private String name;
  private String parentBoneId;
  private String vmcBoneName;
  private String modelUrl;

  public String getId() { return id; }

  public void setId(String id) { this.id = id; }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public String getParentBoneId() { return parentBoneId; }

  public void setParentBoneId(String parentBoneId) { this.parentBoneId = parentBoneId; }

  public String getVmcBoneName() { return vmcBoneName; }

  public void setVmcBoneName(String vmcBoneName) { this.vmcBoneName = vmcBoneName; }

  public String getModelUrl() { return modelUrl; }

  public void setModelUrl(String modelUrl) { this.modelUrl = modelUrl; }


  public PluginBoneRegistrationT() {
    this.id = null;
    this.name = null;
    this.parentBoneId = null;
    this.vmcBoneName = null;
    this.modelUrl = null;
  }
}

