// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PluginBonesUpdateResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static PluginBonesUpdateResponse getRootAsPluginBonesUpdateResponse(ByteBuffer _bb) { return getRootAsPluginBonesUpdateResponse(_bb, new PluginBonesUpdateResponse()); }
  public static PluginBonesUpdateResponse getRootAsPluginBonesUpdateResponse(ByteBuffer _bb, PluginBonesUpdateResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PluginBonesUpdateResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.rpc.PluginBoneRegistration registeredPluginBones(int j) { return registeredPluginBones(new solarxr_protocol.rpc.PluginBoneRegistration(), j); }
  public solarxr_protocol.rpc.PluginBoneRegistration registeredPluginBones(solarxr_protocol.rpc.PluginBoneRegistration obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int registeredPluginBonesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.rpc.PluginBoneRegistration.Vector registeredPluginBonesVector() { return registeredPluginBonesVector(new solarxr_protocol.rpc.PluginBoneRegistration.Vector()); }
  public solarxr_protocol.rpc.PluginBoneRegistration.Vector registeredPluginBonesVector(solarxr_protocol.rpc.PluginBoneRegistration.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPluginBonesUpdateResponse(FlatBufferBuilder builder,
      int registeredPluginBonesOffset) {
    builder.startTable(1);
    PluginBonesUpdateResponse.addRegisteredPluginBones(builder, registeredPluginBonesOffset);
    return PluginBonesUpdateResponse.endPluginBonesUpdateResponse(builder);
  }

  public static void startPluginBonesUpdateResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRegisteredPluginBones(FlatBufferBuilder builder, int registeredPluginBonesOffset) { builder.addOffset(0, registeredPluginBonesOffset, 0); }
  public static int createRegisteredPluginBonesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRegisteredPluginBonesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPluginBonesUpdateResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PluginBonesUpdateResponse get(int j) { return get(new PluginBonesUpdateResponse(), j); }
    public PluginBonesUpdateResponse get(PluginBonesUpdateResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public PluginBonesUpdateResponseT unpack() {
    PluginBonesUpdateResponseT _o = new PluginBonesUpdateResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(PluginBonesUpdateResponseT _o) {
    solarxr_protocol.rpc.PluginBoneRegistrationT[] _oRegisteredPluginBones = new solarxr_protocol.rpc.PluginBoneRegistrationT[registeredPluginBonesLength()];
    for (int _j = 0; _j < registeredPluginBonesLength(); ++_j) {_oRegisteredPluginBones[_j] = (registeredPluginBones(_j) != null ? registeredPluginBones(_j).unpack() : null);}
    _o.setRegisteredPluginBones(_oRegisteredPluginBones);
  }
  public static int pack(FlatBufferBuilder builder, PluginBonesUpdateResponseT _o) {
    if (_o == null) return 0;
    int _registeredPluginBones = 0;
    if (_o.getRegisteredPluginBones() != null) {
      int[] __registeredPluginBones = new int[_o.getRegisteredPluginBones().length];
      int _j = 0;
      for (solarxr_protocol.rpc.PluginBoneRegistrationT _e : _o.getRegisteredPluginBones()) { __registeredPluginBones[_j] = solarxr_protocol.rpc.PluginBoneRegistration.pack(builder, _e); _j++;}
      _registeredPluginBones = createRegisteredPluginBonesVector(builder, __registeredPluginBones);
    }
    return createPluginBonesUpdateResponse(
      builder,
      _registeredPluginBones);
  }
}

