// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * OSC Settings that are used for spatial headphone processing
 */
@SuppressWarnings("unused")
public final class SpatialHeadphonesOscSettings extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static SpatialHeadphonesOscSettings getRootAsSpatialHeadphonesOscSettings(ByteBuffer _bb) { return getRootAsSpatialHeadphonesOscSettings(_bb, new SpatialHeadphonesOscSettings()); }
  public static SpatialHeadphonesOscSettings getRootAsSpatialHeadphonesOscSettings(ByteBuffer _bb, SpatialHeadphonesOscSettings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SpatialHeadphonesOscSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enabled() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int portOut() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public String address() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer addressAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer addressInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createSpatialHeadphonesOscSettings(FlatBufferBuilder builder,
      boolean enabled,
      int portOut,
      int addressOffset) {
    builder.startTable(3);
    SpatialHeadphonesOscSettings.addAddress(builder, addressOffset);
    SpatialHeadphonesOscSettings.addPortOut(builder, portOut);
    SpatialHeadphonesOscSettings.addEnabled(builder, enabled);
    return SpatialHeadphonesOscSettings.endSpatialHeadphonesOscSettings(builder);
  }

  public static void startSpatialHeadphonesOscSettings(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addEnabled(FlatBufferBuilder builder, boolean enabled) { builder.addBoolean(0, enabled, false); }
  public static void addPortOut(FlatBufferBuilder builder, int portOut) { builder.addShort(1, (short) portOut, (short) 0); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addOffset(2, addressOffset, 0); }
  public static int endSpatialHeadphonesOscSettings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SpatialHeadphonesOscSettings get(int j) { return get(new SpatialHeadphonesOscSettings(), j); }
    public SpatialHeadphonesOscSettings get(SpatialHeadphonesOscSettings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public SpatialHeadphonesOscSettingsT unpack() {
    SpatialHeadphonesOscSettingsT _o = new SpatialHeadphonesOscSettingsT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(SpatialHeadphonesOscSettingsT _o) {
    boolean _oEnabled = enabled();
    _o.setEnabled(_oEnabled);
    int _oPortOut = portOut();
    _o.setPortOut(_oPortOut);
    String _oAddress = address();
    _o.setAddress(_oAddress);
  }
  public static int pack(FlatBufferBuilder builder, SpatialHeadphonesOscSettingsT _o) {
    if (_o == null) return 0;
    int _address = _o.getAddress() == null ? 0 : builder.createString(_o.getAddress());
    return createSpatialHeadphonesOscSettings(
      builder,
      _o.getEnabled(),
      _o.getPortOut(),
      _address);
  }
}

