// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class SpatialHeadphonesOscSettingsT {
  private boolean enabled;
  private int portOut;
  private String address;

  public boolean getEnabled() { return enabled; }

  public void setEnabled(boolean enabled) { this.enabled = enabled; }

  public int getPortOut() { return portOut; }

  public void setPortOut(int portOut) { this.portOut = portOut; }

  public String getAddress() { return address; }

  public void setAddress(String address) { this.address = address; }


  public SpatialHeadphonesOscSettingsT() {
    this.enabled = false;
    this.portOut = 0;
    this.address = null;
  }
}

