// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import dev.slimevr.fbscodegen.runtime.FlatBufferReader
import dev.slimevr.fbscodegen.runtime.FlatBufferWriter
import kotlin.Int

@Suppress(\"unused\")
class GetPluginBonesRequest private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val GetPluginBonesRequest: UByte = 134u
        val names : Array<String> = arrayOf(\"NONE\", \"GetPluginBonesRequest\")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}

@Suppress(\"unused\")
class GetPluginBonesResponse private constructor() {
    public val bones: List<PluginBone>? = null

    public fun encode(builder: FlatBufferWriter): Int {
        val __off_bones = bones?.let { builder.createVectorOfTables(it.map { e -> e.encode(builder) }.toIntArray()) }

        builder.startTable(1)
        __off_bones?.let { builder.addOffset(0, it, 0) }
        return builder.endTable()
    }

    public companion object {
        public fun decode(bb: FlatBufferReader, tableOffset: Int): GetPluginBonesResponse {
            val vtableOffset = tableOffset - bb.getInt(tableOffset)
            val vtableSize = bb.getShort(vtableOffset).toInt()

            val __offset_bones = if (vtableSize > 4) bb.getShort(vtableOffset + 4).toInt() else 0

            return GetPluginBonesResponse(
                bones = if (__offset_bones != 0) { 
                    val vecOff = tableOffset + __offset_bones + bb.getInt(tableOffset + __offset_bones)
                    val len = bb.getInt(vecOff)
                    (0 until len).mapNotNull { i -> 
                        if (bb.getInt(vecOff + 4 + i * 4) != 0) 
                            PluginBone.decode(bb, vecOff + 4 + i * 4 + bb.getInt(vecOff + 4 + i * 4)) 
                        else null 
                    }
                } else null
            )
        }
    }
}
