// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress(\"unused\")
class GetPluginBonesRequest private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val GetPluginBonesRequest: UByte = 134u
        val names : Array<String> = arrayOf(\"NONE\", \"GetPluginBonesRequest\")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
